name: Build MacOs Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest   
    steps:
      - name: install dependencies
        run: |
         sudo apt-get install curl build-essential gcc make mingw-w64 -y
         sudo apt-get install rustc cargo gzip -y
         sudo apt-get install g++ zlib1g-dev libmpc-dev libmpfr-dev  libgmp-dev snapd
         sudo snap  install zig --beta --classic 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list_targets
        run: |
          rustup target list

      - name: add_targets
        run: |
          rustup target add x86_64-apple-darwin 
          rustup target add aarch64-apple-darwin
          cargo install --locked cargo-zigbuild
          
      - name: compile macos
        run: |
          cargo zigbuild --target x86_64-apple-darwin --release
          cargo zigbuild --target aarch64-apple-darwin --release

          
      - name: list binary
        run: |
          ls target/x86_64-apple-darwin/release
          ls target/aarch64-apple-darwin/release

      - name: rename binaries 
        run: |
          cp target/x86_64-apple-darwin/release/hello_rust target/x86_64-apple-darwin/release/hello_rust_macos_intel
          cp target/x86_64-apple-darwin/release/hello_rust target/aarch64-apple-darwin/release/hello_rust_macos_silicon
          
      - name: upload binary intel to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/x86_64-apple-darwin/release/hello_rust_macos_intel'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: upload binary silicon to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/aarch64-apple-darwin/release/hello_rust_macos_silicon'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

   


   
